version: "2.2"
services:
  chainsync:
    image: coinservice
    build:
      context: ./csv
      dockerfile: Dockerfile
    volumes:
      - ./data/chain:/home/chain
    working_dir: /home
    entrypoint: [./run.sh]
    environment:
      INDEXERID: -1
      MODE: "chainsync"
    env_file:
      - service.env
    depends_on:
      - mongo
      - coordinator

  query:
    image: coinservice
    working_dir: /home
    entrypoint: [./run.sh]
    environment:
      INDEXERID: 0
      MODE: "query"
    env_file:
      - service.env
    depends_on:
      - mongo
      - coordinator

  indexer:
    image: coinservice
    working_dir: /home
    entrypoint: [./run.sh]
    environment:
      INDEXERID: 0
      MODE: "indexer"
    env_file:
      - service.env
    depends_on:
      - chainsync
      - mongo
      - coordinator

  worker:
    image: coinservice
    scale: 1
    working_dir: /home
    entrypoint: [./run.sh]
    environment:
      INDEXERID: 0
      MODE: "indexworker"
    env_file:
      - service.env
    depends_on:
      - indexer
      - coordinator

  liquidity-processor:
    image: coinservice
    working_dir: /home
    entrypoint: [./run.sh]
    environment:
      INDEXERID: 0
      MODE: "liquidity"
    env_file:
      - service.env
    depends_on:
      - chainsync
      - mongo
      - coordinator

  trade-processor:
    image: coinservice
    working_dir: /home
    entrypoint: [./run.sh]
    environment:
      INDEXERID: 0
      MODE: "trade"
    env_file:
      - service.env
    depends_on:
      - chainsync
      - mongo
      - coordinator

  shield-processor:
    image: coinservice
    working_dir: /home
    entrypoint: [./run.sh]
    environment:
      INDEXERID: 0
      MODE: "shield"
    env_file:
      - service.env
    depends_on:
      - chainsync
      - mongo
      - coordinator

  assistant:
    image: coinservice
    working_dir: /home
    entrypoint: [./run.sh]
    environment:
      INDEXERID: 0
      MODE: "assistant"
    env_file:
      - service.env
    depends_on:
      - chainsync
      - mongo
      - coordinator
  coordinator:
    image: coinservice
    volumes:
      - ./data/mongodump:/home/mongodump
    working_dir: /home
    entrypoint: [./run.sh]
    environment:
      INDEXERID: 0
      MODE: "coordinator"
    env_file:
      - service.env
    depends_on:
      - mongo

  nginx-server:
    image: nginx-load-balancer
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 6002:80
    restart: unless-stopped
    depends_on:
      - query
      - indexer
      - coordinator

  # watcher:
  #   image: alpine
  #   volumes:
  #     - .:/home
  #   entrypoint: [/home/servicewatcher]
  #   environment:
  #     SLACKHOOKCSV: ""
  #     CSVSYNCKER: "http://chainsyncv3:9001"
  #     FULLNODE: "http://51.161.119.66:9334"
  #   depends_on:
  #     - chainsyncv3

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data/mongodb:/data/db
      - ./data/mongodb_config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 6001:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
